# Generated by Django 5.1.1 on 2024-09-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
